### 注册用户
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}


### 登录
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}

### 获取当前用户信息
GET http://localhost:8080/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc4MTM5MTMxMiwiZXhwIjoxNzgxNDc3NzEyfQ.LfdHMNWH6Pi1E3euV14Jy1lBJpwZ0fcbcZptB-9einI





